export { default as Logo } from './logo_ups.png'  
export { default as Logo2 } from "./pancasakti_navbar.png"
export { default as Header } from "./header.png"
export { default as LogoHeader } from './pancasakti_header.png'
export { default as Indonesia } from "./Indonesia.png"
export { default as English } from "./English.png"
export { default as LogoNew } from "./pancasakti_new.png"
export { default as AboutHeader } from './about_header.png'
export { default as Rektor } from './rektor.jpeg'
export { default as Brosur } from './brosur.png'
export { default as Pmb } from './pmb.png'
export { default as Pmb2 } from './pmb2.jpeg'
export { default as Pmb3 } from './pmb3.jpeg'
